# Generated by Django 3.1.14 on 2024-05-04 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sandy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=50)),
                ('major', models.CharField(max_length=30)),
                ('period', models.CharField(max_length=10)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('networking', models.TextField()),
                ('sysadmin', models.TextField()),
                ('server_infrastructure', models.TextField()),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='about',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='category',
        ),
        migrations.RemoveField(
            model_name='home',
            name='greetings_1',
        ),
        migrations.RemoveField(
            model_name='home',
            name='greetings_2',
        ),
        migrations.RemoveField(
            model_name='home',
            name='name',
        ),
        migrations.RemoveField(
            model_name='home',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='link',
        ),
        migrations.AddField(
            model_name='home',
            name='description',
            field=models.TextField(default='SOME STRING'),
        ),
        migrations.AddField(
            model_name='home',
            name='heading',
            field=models.CharField(default='SOME STRING', max_length=50),
        ),
        migrations.AddField(
            model_name='home',
            name='name_1',
            field=models.CharField(default='first name', max_length=50),
        ),
        migrations.AddField(
            model_name='home',
            name='name_2',
            field=models.CharField(default='last name', max_length=50),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='description',
            field=models.TextField(default='SOME STRING'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='project',
            field=models.CharField(default='project name', max_length=50),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='vendor',
            field=models.CharField(default='vendor name', max_length=20),
        ),
        migrations.DeleteModel(
            name='About',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='Skills',
        ),
    ]
