# Generated by Django 3.1.14 on 2024-05-04 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sandy', '0003_auto_20240504_0315'),
    ]

    operations = [
        migrations.RenameField(
            model_name='home',
            old_name='name_1',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='home',
            old_name='name_2',
            new_name='last_name',
        ),
    ]
