# Generated by Django 3.1.14 on 2024-05-04 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sandy', '0004_auto_20240504_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='skills_desc',
            field=models.TextField(default=''),
        ),
    ]
