# Generated by Django 3.1.14 on 2024-05-04 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sandy', '0005_education_skills_desc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='description',
            new_name='description_1',
        ),
        migrations.RenameField(
            model_name='portfolio',
            old_name='image',
            new_name='image_1',
        ),
        migrations.RenameField(
            model_name='portfolio',
            old_name='project',
            new_name='project_1',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='vendor',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='description_2',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='description_3',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='image_2',
            field=models.ImageField(default='', upload_to='portfolio/'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='image_3',
            field=models.ImageField(default='', upload_to='portfolio/'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='project_2',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='project_3',
            field=models.CharField(default='', max_length=50),
        ),
    ]
