# Generated by Django 3.1.14 on 2024-05-04 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sandy', '0006_auto_20240504_1023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='institution',
            new_name='institution_1',
        ),
        migrations.RenameField(
            model_name='education',
            old_name='major',
            new_name='major_1',
        ),
        migrations.RemoveField(
            model_name='education',
            name='period',
        ),
        migrations.AddField(
            model_name='education',
            name='end_1',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='education',
            name='end_2',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='education',
            name='institution_2',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='education',
            name='major_2',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='education',
            name='start_1',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='education',
            name='start_2',
            field=models.CharField(default='', max_length=10),
        ),
    ]
